### ISSUE TITLE
Digfort script does not work on Linux (for some blueprints)

### ISSUE THREAD

**Issue by MurKit** [DFHack/dfhack#1179]
I'm using DFHack version 0.43.05-r2 (release) on x86_64 shipped with LinuxLNP-0.43.05-r06.
Csv file is from Community Quickfort Blueprints v2.3, but just renamed.

```
[DFHack]# digfort /home/machine/Downloads/LinuxLNP-0.43.05-r06/1.csv 
E: NoMethodError: undefined method `shape_basic' for nil:NilClass
 /home/machine/Downloads/LinuxLNP-0.43.05-r06/df_linux/hack/scripts/digfort.rb:78
 /home/machine/Downloads/LinuxLNP-0.43.05-r06/df_linux/hack/scripts/digfort.rb:76:in `each'
 /home/machine/Downloads/LinuxLNP-0.43.05-r06/df_linux/hack/scripts/digfort.rb:76
 /home/machine/Downloads/LinuxLNP-0.43.05-r06/df_linux/hack/scripts/digfort.rb:74:in `each'
 /home/machine/Downloads/LinuxLNP-0.43.05-r06/df_linux/hack/scripts/digfort.rb:74
 (eval):45:in `load'
 (eval):45
 (eval):45:in `catch'
```

How to fix that?

Edit:
Some of the files don't cause the error.
75-3-Living Pods_Fix.csv file works fine. 
But these do cause an error:
81-3-Savokis_Leaf-dig.csv
100-4-Vherid.csv

**Comment by lethosor** [comment]
Looks like I forgot to close this, but it should be fixed
