### ISSUE TITLE
Game crashes, how to diagnose?

### ISSUE THREAD

**Issue by matt32106** [DFHack/dfhack#1428]
HI,
I am running PyLNP 0.44.12 on Ubuntu 18.04 LTS. My game keeps crashing a few minutes after the current save. Is there a debugging guide somewhere to help me diagnose the source of the problem? 
The logs I have found are not very talkative.

[errorlog.txt](https://github.com/DFHack/dfhack/files/2757403/errorlog.txt)
[gamelog.txt](https://github.com/DFHack/dfhack/files/2757404/gamelog.txt)
[stderr.log](https://github.com/DFHack/dfhack/files/2757405/stderr.log)
[stdout.log](https://github.com/DFHack/dfhack/files/2757406/stdout.log)

**Comment by matt32106** [comment]
I tried gdb but know nothing about it:

```
hippo@hippo-camp:~/Desktop/LinuxLNP-0.44.12-r02/df_linux$ gdb ./libs/Dwarf_Fortress 
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./libs/Dwarf_Fortress...(no debugging symbols found)...done.
(gdb) run
Starting program: /home/hippo/Desktop/LinuxLNP-0.44.12-r02/df_linux/libs/Dwarf_Fortress 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffe8494700 (LWP 5519)]
[New Thread 0x7fffe7c93700 (LWP 5520)]
[New Thread 0x7fffe7492700 (LWP 5521)]
[New Thread 0x7fffe6c91700 (LWP 5522)]
[New Thread 0x7fffe6490700 (LWP 5523)]
Sound devices available:
OpenAL Soft
Picking OpenAL Soft. If your desired device was missing, make sure you have the appropriate 32-bit libraries installed. If you wanted a different device, configure ~/.openalrc appropriately.
[New Thread 0x7ffff7f31700 (LWP 5524)]
[Thread 0x7ffff7f31700 (LWP 5524) exited]
[New Thread 0x7fffe5599700 (LWP 5525)]
[New Thread 0x7fffe5599700 (LWP 5526)]
[Thread 0x7fffe5599700 (LWP 5525) exited]
[New Thread 0x7fffe4d98700 (LWP 5527)]
Perfect OpenAL context attributes GET
Loading bindings from data/init/interface.txt
Resetting textures
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Resetting textures

Thread 6 "Dwarf_Fortress" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe6490700 (LWP 5523)]
0x000000000047e5d0 in ?? ()
(gdb) bt
#0  0x000000000047e5d0 in  ()
#1  0x0000000000000000 in  ()
(gdb) 
```

**Comment by lethosor** [comment]
Launch with ./df. ./libs/Dwarf_Fortress should never be run directly.

**Comment by matt32106** [comment]
If I start with df, gdb complains that the file format is not executable :/
`
"/home/hippo/Desktop/LinuxLNP-0.44.12-r02/df_linux/df": not in executable format: File format not recognised
`

**Comment by lethosor** [comment]
Don't start it in gdb. It's a shell script.

**Comment by matt32106** [comment]
I normally use LNP to launch df, but here I was trying to get more info about the segfault.
How can I get debug info then?

**Comment by lethosor** [comment]
My first step would be to run ./df, by itself, and see if the crash still occurs.

**Comment by matt32106** [comment]
Yes it does crash 2-3 minutes after game start, same behavior as with lnp.

**Comment by lethosor** [comment]
Ok, it's not a DFHack issue then, if it doesn't occur with DFHack loaded. Unfortunately that makes it harder to debug, since our ability to debug DF is very limited. It's possible that you're experiencing a known crash with some workaround on the DF bug tracker, so you could check there.

**Comment by matt32106** [comment]
OK, I'll test my luck on their bugtracker.
