### ISSUE TITLE
ban-cooking seeds error

### ISSUE THREAD

**Issue by cdombroski** [DFHack/dfhack#1623]
DFHack version 0.47.04-r2 (release) on x86_64

```
[DFHack]# ban-cooking seeds
E: ArgumentError: invalid enum member seed of DFHack::PlantMaterialDef
 C:/Users/cdombroski/df/PeridexisErrant's Starter Pack 0.47.04-r07/Dwarf Fortress 0.47.04/hack/ruby/ruby-autogen-defs.rb:239:in `int'
 C:/Users/cdombroski/df/PeridexisErrant's Starter Pack 0.47.04-r07/Dwarf Fortress 0.47.04/hack/ruby/ruby-autogen-defs.rb:483:in `[]'
 hack/scripts/ban-cooking.rb:121:in `block (2 levels) in <top (required)>'
 C:/Users/cdombroski/df/PeridexisErrant's Starter Pack 0.47.04-r07/Dwarf Fortress 0.47.04/hack/ruby/ruby-autogen-defs.rb:439:in `block in each'
 C:/Users/cdombroski/df/PeridexisErrant's Starter Pack 0.47.04-r07/Dwarf Fortress 0.47.04/hack/ruby/ruby-autogen-defs.rb:439:in `each'
 C:/Users/cdombroski/df/PeridexisErrant's Starter Pack 0.47.04-r07/Dwarf Fortress 0.47.04/hack/ruby/ruby-autogen-defs.rb:439:in `each'
 hack/scripts/ban-cooking.rb:119:in `each_with_index'
 hack/scripts/ban-cooking.rb:119:in `block in <top (required)>'
```

**Comment by lethosor** [comment]
Looks like an issue with dfhack/scripts@792ae44ab14afd3a2b3e850a6fcb463d714b0a44 - ruby codegen converts enum items to PascalCase:

```ruby
class PlantMaterialDef < MemHack::Enum
    ENUM = Hash.new
    NUME = Hash.new
    ENUM[0] = :BasicMat ; NUME[:BasicMat] = 0
    ENUM[1] = :Tree ; NUME[:Tree] = 1
    ENUM[2] = :Drink ; NUME[:Drink] = 2
    ENUM[3] = :Seed ; NUME[:Seed] = 3
    ENUM[4] = :Thread ; NUME[:Thread] = 4
    ENUM[5] = :Mill ; NUME[:Mill] = 5
    ENUM[6] = :ExtractVial ; NUME[:ExtractVial] = 6
    ENUM[7] = :ExtractBarrel ; NUME[:ExtractBarrel] = 7
    ENUM[8] = :ExtractStillVial ; NUME[:ExtractStillVial] = 8
end
```
