### ISSUE TITLE
Prevent crash if DFHack GUI window is open when exiting fort

### ISSUE THREAD

**Issue by myk002** [DFHack/dfhack#4183]
to reproduce:
1. open gui/reveal when a fort is loaded
2. click on the map to defocus the window
3. go to settings, quit without saving

example backtrace:
```c
#0  0x0000000001033222 in ?? ()
#1  0x0000000001384f7d in ?? ()
#2  0x00000000010db714 in ?? ()
#3  0x00007fffedae3bcc in viewscreen_overlay<df::viewscreen_dwarfmodest>::interpose_fn_render (this=0x7fff4f7e0580)
    at /home/myk/src/dfhack/plugins/overlay.cpp:92
#4  0x00007ffff77b80d4 in df::function_identity<void (df::abstract_interfacest::*)()>::invoke(lua_State*, int) ()
   from ./hack/libdfhack.so
#5  0x00007ffff76c414d in DFHack::LuaWrapper::method_wrapper_core (state=0x7fffe8034ce8, id=0x2a37860)
    at /home/myk/src/dfhack/library/LuaTypes.cpp:1225
#6  0x00007ffff67c9200 in luaD_precall (L=L@entry=0x7fffe8034ce8, func=func@entry=0x7fffe8788370, 
    nresults=nresults@entry=0) at /home/myk/src/dfhack/depends/lua/src/ldo.c:434
#7  0x00007ffff67e0514 in luaV_execute (L=L@entry=0x7fffe8034ce8)
    at /home/myk/src/dfhack/depends/lua/src/lvm.c:1134
#8  0x00007ffff67c9528 in luaD_call (nResults=0, func=<optimized out>, L=0x7fffe8034ce8)
    at /home/myk/src/dfhack/depends/lua/src/ldo.c:499
#9  luaD_callnoyield (L=L@entry=0x7fffe8034ce8, func=<optimized out>, nResults=nResults@entry=0)
    at /home/myk/src/dfhack/depends/lua/src/ldo.c:509
#10 0x00007ffff67bf7a4 in lua_callk (L=0x7fffe8034ce8, nargs=<optimized out>, nresults=0, ctx=0, k=0x0)
    at /home/myk/src/dfhack/depends/lua/src/lapi.c:925
#11 0x00007ffff79a7124 in DFHack::dfhack_lua_viewscreen::do_render (L=0x7fffe8034ce8)
    at /home/myk/src/dfhack/library/modules/Screen.cpp:934
```

**Comment by myk002** [comment]
Discord discussion: https://discord.com/channels/793331351645323264/807443262704058408/1197364716666896425

**Comment by RebOOter** [comment]
[crash_2025-06-20-08-56-40.txt](https://github.com/user-attachments/files/20839047/crash_2025-06-20-08-56-40.txt)
Here are some logs from this crash. 
I can say that it happens no matter the focus. Just opening any DFHack window (from mods too) will be enough.
Here is the [conversation](https://discord.com/channels/793331351645323264/807444467140788254/1385515012738646029)
